apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: qdrant-hooks
  namespace: kasten-io
actions:
  backupPrehook:
    phases:
    - func: KubeTask
      name: lockQdrant
      args:
        namespace: "{{ .StatefulSet.Namespace }}"
        image: curlimages/curl
        command:
        - sh
        - -c
        - |
          curl --location 'http://qdrant:6333/locks' \
          --header 'Content-Type: application/json' \
          --data '{
              "error_message": "write is temporarily disabled while a Kasten backup is performed",
              "write": true
          }'
  backupPosthook:
    phases:
    - func: KubeTask
      name: unlockQdrant
      args:
        namespace: "{{ .StatefulSet.Namespace }}"
        image: curlimages/curl
        command:
        - sh
        - -c
        - |
          curl --location 'http://qdrant:6333/locks' \
          --header 'Content-Type: application/json' \
          --data '{
              "write": false
          }'