apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: qdrant-hooks
actions:
  backupPrehook:
    phases:
    - func: KubeExec
      name: lockQdrant
      args:
        namespace: "{{ .StatefulSet.Namespace }}"
        pod: "{{ index .StatefulSet.Pods 0 }}"
        container: qdrant
        command:
        - bash
        - -o
        - errexit
        - -o
        - pipefail
        - -c
        - |
          curl --location 'http://localhost:6333/locks' \
          --header 'Content-Type: application/json' \
          --data '{
              "error_message": "write is temporarily disabled while a Kasten backup is performed",
              "write": true
          }'
  backupPosthook:
    phases:
    - func: KubeExec
      name: unlockQdrant
      args:
        namespace: "{{ .StatefulSet.Namespace }}"
        pod: "{{ index .StatefulSet.Pods 0 }}"
        container: qdrant
        command:
        - bash
        - -o
        - errexit
        - -o
        - pipefail
        - -c
        - |
          curl --location 'http://localhost:6333/locks' \
          --header 'Content-Type: application/json' \
          --data '{
              "write": false
          }'