{{- if and .Values.qdrant.enabled .Values.qdrant.populateJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k10animalai.fullname" . }}-populate-qdrant
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k10animalai.labels" . | nindent 4 }}
    app.kubernetes.io/component: populate-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "k10animalai.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: populate-job
    spec:
      restartPolicy: OnFailure
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
      - name: wait-for-qdrant
        image: busybox:1.35
        command: 
        - sh
        - -c
        - |
          echo "Waiting for Qdrant to be ready..."
          until nc -z {{ include "k10animalai.qdrantHost" . }} {{ .Values.qdrant.port }}; do
            echo "Qdrant not ready, sleeping 5s..."
            sleep 5
          done
          echo "Qdrant is ready!"
      containers:
      - name: populate-qdrant
        image: {{ include "k10animalai.image" . }}
        imagePullPolicy: {{ .Values.k10animalai.image.pullPolicy }}
        command:
        - python
        - /scripts/populate_qdrant.py
        env:
        - name: QDRANT_HOST
          value: {{ include "k10animalai.qdrantHost" . | quote }}
        - name: QDRANT_PORT
          value: {{ .Values.qdrant.port | quote }}
        volumeMounts:
        - name: populate-script
          mountPath: /scripts
          readOnly: true
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: populate-script
        configMap:
          name: {{ include "k10animalai.fullname" . }}-populate-script
          defaultMode: 0755
{{- end }}
